Repository OneBusAway/onebusaway-gtfs-modules, pull requests merged in 2025-06, with the labels that each got.

#354 Parse seconds without regexp
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/serialization/mappings/StopTimeFieldMappingFactory.java
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/gtfs/LegacyStopTimeFieldMappingFactory.java
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/gtfs/ParseBenchmark.java
Labels: Performance

#355 Reuse object mapper
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/serialization/LocationsGeoJSONReader.java
Labels: Performance

#361 Improve delimited text parser (CSV parsing)
  .gitignore
  onebusaway-csv-entities/src/main/java/org/onebusaway/csv_entities/CSVLibrary.java
  onebusaway-csv-entities/src/main/java/org/onebusaway/csv_entities/CSVListener.java
  onebusaway-csv-entities/src/main/java/org/onebusaway/csv_entities/DelimitedTextParser.java
  onebusaway-csv-entities/src/test/java/org/onebusaway/csv_entities/CSVLibraryTest.java
  onebusaway-csv-entities/src/test/java/org/onebusaway/csv_entities/DelimitedTextParserTest.java
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/serialization/GtfsReader.java
  onebusaway-gtfs/src/test/java/org/onebusaway/gtfs/serialization/GtfsReaderTest.java
  onebusaway-jmh/README.md
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/BenchmarkMain.java
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/csv/CsvLineParserBenchmark.java
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/csv/LegacyDelimitedTextParser.java
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/gtfs/GtfsSingleShotBenchmark.java
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/gtfs/GtfsThroughputBenchmark.java
  onebusaway-jmh/src/main/java/org/onebusaway/jmh/gtfs/ParseStopTimeBenchmark.java
Labels: Breaking change, Performance

#359 Remove non-standard fields in trip and `notes.txt`
  onebusaway-gtfs-transformer/src/main/java/org/onebusaway/gtfs_transformer/factory/TransformFactory.java
  onebusaway-gtfs-transformer/src/main/java/org/onebusaway/gtfs_transformer/impl/CompareToReferenceService.java
  onebusaway-gtfs-transformer/src/main/java/org/onebusaway/gtfs_transformer/impl/UpdateCalendarDatesForDuplicateTrips.java
  onebusaway-gtfs-transformer/src/main/java/org/onebusaway/gtfs_transformer/impl/UpdateTripHeadsignByReference.java
  onebusaway-gtfs-transformer/src/main/java/org/onebusaway/gtfs_transformer/impl/UpdateTripIdById.java
  onebusaway-gtfs-transformer/src/main/java/org/onebusaway/gtfs_transformer/impl/UpdateTripsForSdon.java
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/AgencyAndId.java
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/AgencyAndIdInstance.java
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/Note.java
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/Trip.java
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/serialization/GtfsEntitySchemaFactory.java
  onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/serialization/GtfsReader.java
  onebusaway-gtfs/src/test/java/org/onebusaway/gtfs/serialization/GtfsReaderTest.java
Labels: Breaking change
